version: "3"
services:
#  assistant:
#    image: docker-registry.active911.com:5000/bryan.walcott/assistant:latest
#    depends_on:
#      - "influxdb"
#      - "grafana"
#    volumes:
#      - ./data/assistant:/data/assistant
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 5
#        window: 120s
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - "influxdb"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    volumes:
      - ./data/grafana:/var/lib/grafana
  influxdb:
    image: influxdb:1.3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

